- Ultimate_Cataclysm/gfx/UltimateCataclysm/pngs_large_64x64/monsters/mon_ant_soldier/mon_ant_soldier.json
Prevented soldier ant tiles from showing up.
> Fix typo solider -> soldier

- Ultimate_Cataclysm/gfx/UltimateCataclysm/pngs_giant_96x96/terrain/t_tree/t_tree.json
- Ultimate_Cataclysm/gfx/UltimateCataclysm/pngs_large_64x64/terrain/t_tree_young/tree_young.json
- Ultimate_Cataclysm/gfx/UltimateCataclysm/pngs_normal_32x32/terrain/t_shrub/t_shrub.json
- Ultimate_Cataclysm/gfx/UltimateCataclysm/tile_info.json
Obvious missing things still (once the current `looks_like` PRs for the game are merged) are tree trunks and tree stumps in the forest
And lilypads, cattails, and the salt water versions of the water tiles in the swamp
> Fixes so the tileset will compose again

- .github/workflows/make_release.yml
This PR adds a github action that can be used to automatically build and release versions of this tileset.
The current most recent ubuntu version that github actions offers doesn't provide a recent enough version of libvips, so I used a nice alpine linux container to run everything in.
To trigger a release just checkout the branch you want to release and run
```
git tag v1.2.1
git push origin v1.2.1
```
and the action will start a build then create a release.
Note that the tag must start with a `v`, tags starting with any other character will be ignored.
> Create github action to deploy releases

- .github/workflows/make_release.yml
- Ultimate_Cataclysm/gfx/UltimateCataclysm/tile_info.json
The github action now creates a draft release with the archive uploaded instead of releasing automatically.  This allows for greater flexibility and worry-free testing of the action.
I also fixed a json error that just got merged so this will run, guess my next job is adding CI for pull requests.
> Create draft release to allow easy manual editing before publish

- .github/workflows/ci_build.yml
It looks like https://github.com/CleverRaven/Cataclysm-DDA/pull/39744 broke the CI script here.
If so, this will fix it.
> Update CI for compose.py changes

- gfx/UltimateCataclysm/pngs_incomplete_32x32/vehicle/doors/vp_door.json
a bunch of vehicle doors repeated `rotS` in their definitions for the open state
replaced those with `rotE` where appropriate
before:
after:
> correct rotation data for vehicle doors in ultica

- .github/workflows/ci_build.yml
A new option from https://github.com/CleverRaven/Cataclysm-DDA/pull/46358 that shows what fillers are no longer needed and can be removed.
> Use compose.py --obsolete-fillers

- gfx/BrownLikeBears/tile_info.json
BLB "Fix offset of big monsters"
Fix offset of big monster so they occupy the lower right corner of ther sprite
**Before**
**After**
> [BLB] Fix offset of big monsters

- gfx/UltimateCataclysm/pngs_fillerhoder_32x32/MShockXotto+/terrain/t_pit_corpsed.json
- gfx/UltimateCataclysm/pngs_normal_32x32/terrain/t_dirt/t_dirt.png
Ultica "Remove unused t_dirt"
Remove `t_dirt.png` In preparation for https://github.com/CleverRaven/Cataclysm-DDA/pull/48125
It was placed in a main tilesheet but only used in one filler.
> Remove t_dirt in preparation for the new compose.py

- gfx/Chibi_Ultica/pngs_ChibiNormalCharacterMagiclysm_32x32
- gfx/Chibi_Ultica/tile_info.json
Chibi-Ultica "Add Magiclysm Character overlays to Chibi Ultica"
Add content from https://github.com/I-am-Erk/CDDA-Tilesets/pull/644 and https://github.com/I-am-Erk/CDDA-Tilesets/pull/645 to Chibi Ultica
> [Chibi-Ultica] Add Magiclysm Character overlays to Chibi Ultica

- gfx/UltimateCataclysm/pngs_large_64x64/overmap/forest_thick.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/natural.json
Ultica "json for "special" otr"
Adds json for "special" overmap terrain, which seems to be used for isherwood quest. This is still an incomplete task because some terrain tiles are still missing altogether, but it's an improvement
> Ultica json for "special" otr

- gfx/Retrodays/pngs_tiles_10x10/vehicle_part/retrodays_tempfix.json
RetroDays "vehicle fix"
Adds sprites to new vehicle part shapes in https://github.com/CleverRaven/Cataclysm-DDA/pull/50632
> Retrodays vehicle fix

- .github/workflows/Chibi_ci_build.yml
- .github/workflows/HitButton_ci_build.yml
- .github/workflows/MD_ci_build.yml
- .github/workflows/Neodays_ci_build.yml
- .github/workflows/Retrodays_ci_build.yml
- .github/workflows/blb_ci_build.yml
- .github/workflows/ci_build.yml
- .github/workflows/hm_build.yml
- .github/workflows/msx_ci_build.yml
None
Clean up composer scripts a bit, based on the edits I made to the cuteclysm composer 
<https://github.com/pixel-32/CDDA-tileset/blob/master/.github/workflows/ci_build.yml>
See comments `//` only found on this diff, explaining the rationale behind these changes.
```diff
diff --git a/.github/workflows/Chibi_ci_build.yml b/.github/workflows/Chibi_ci_build.yml
index d0124447..c6c56a63 100644
--- a/.github/workflows/Chibi_ci_build.yml
+++ b/.github/workflows/Chibi_ci_build.yml
@@ -50,7 +50,7 @@ jobs:
steps:
- name: Install Dependencies
run: |
-          apk add --no-cache musl-dev gcc vips-dev python3-dev zip py3-pip py3-wheel
+          apk add --no-cache musl-dev gcc vips-dev python3-dev py3-pip py3-wheel
// zip package is not used anywhere, remove it. 
// Upload artifacts action …
```
> Update all composer workflows

- tools/add_outline.py
Infrastructure "Add a script to draw black outline around sprites"
Add a script to draw black outline around sprites. Very usefull to mass convert Ultica's sprite to MSX.
see #844 gun sprites
> Add a script to draw black outline around sprites

- .github/workflows/editorconfig_conformance.yml
Infrastructure "Fix CI check detecting tabs in filename lines produced by git diff"
Don't detect lines starting with multiple plus signs.
`git diff -U0 master -- ants.json > /tmp/int/tmp.diff` was enough to reproduce it locally. With any file that was placed inside a directory with a space in the name.
#916
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_whitespace
> Infrastructure "Fix CI check detecting tabs in filename lines produced by git diff"

- gfx/UltimateCataclysm/pngs_normal_32x32/items/clothes/clothes.json
Ultica "Filter mask item uses dust mask sprite"
JSON-only change to the sprite definition for dust mask, turning it into an array with an additional value.
Hopefully a trivial patch to add a sprite for filter masks and get started contributing.
This won't be very consistent with the overlay appearance, but it's
better than nothing!
Great project, excited to contribute more!
> Give filter masks a non-overlay sprite.

- gfx/UltimateCataclysm/pngs_normal_32x32/items/clothes/clothes.json
This reverts commit a9825f9e490ad7f356fc0e4ad6d9fe838cc07b09. Acepleiades
rightly pointed out in the comments of #928 that this change could be
confusing for whoever eventually implements a unique filter mask sprite.
Ultica "Revert Give filter masks a non-overlay sprite."
For the sake of practice, I'm filing this PR and adding a `looks_like`
entry to achieve the same results in the main repository.
Sorry for the extra paperwork!
> Revert "Give filter masks a non-overlay sprite."

- gfx/Chibi_Ultica/pngs_ChibiSmallMonster_20x20
- gfx/Chibi_Ultica/pngs_widemonsters_32x48
- gfx/Chibi_Ultica/pngs_widevehicle_32x48
- gfx/Chibi_Ultica/tile_info.json
Chibi-Ultica "Fix Chibi Ultica"
Add back monster and vehicles that were moved to 32x48 folder
> [Chibi-Ultica] Fix Chibi Ultica

- gfx/Chibi_Ultica/pngs_ChibiNormalMagiclysmItems_32x32
- gfx/Chibi_Ultica/pngs_ChibiSmallMagiclysmItems_20x20
- gfx/Chibi_Ultica/tile_info.json
Chibi-Ultica "Add Magiclysm item filler from MSX"
> [Chibi] Add Magiclysm item filler from MSX

- gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/mutations/overlay_mutation_HOOVES.json
MSX "Change json to fix hooves in chibi ultica"
Fixes [#53982](https://github.com/CleverRaven/Cataclysm-DDA/issues/53982)
Compose.py was getting confused because MSX only defines hooves in generale while Ultica has hooves for female and male
> [MSX] Do some silly json to fix hooves in Chibi Ultica

- gfx/UltimateCataclysm/layering.json
Ultica "Changed format for layering.json"
This content makes the layering.json work with https://github.com/CleverRaven/Cataclysm-DDA/pull/55416
Until that is merged this will break Ultica,
After that is merged without this Ultica will break.
layering still works on my dirty version with https://github.com/CleverRaven/Cataclysm-DDA/pull/55416 included
> swapped format for layering.json

- gfx/NeoDays/pngs_tiles_10x10/items/1st_aid_0.json
- gfx/Retrodays/pngs_tiles_10x10/item/1st_aid_0.json
NeoDays "Update 1st_aid to 1st_aid_box"
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/55547
Make 1st_aid_box use the 1st_aid sprite
We should probably remove 1st_aid at some point since it's obsolete, but doing it this way keep the tileset retro compatible.
> [Retro/Neo Days] Update 1st_aid to 1st_aid_box

- gfx/Chibi_Ultica/tile_info.json
Chibi-Ultica "Use exclude argument part 1: the easy part"
Use the new `exclude` option of the `compose` script where it doesn't require to restructure the folders
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/56602
Thanks to https://github.com/CleverRaven/Cataclysm-DDA/pull/56493 we can now rework Chibi Ultica (and Altica) folder structure
> [Chibi-Ultica] Use exclude argument part 1: the easy part

- gfx/UltimateCataclysm/pngs_small_20x20/items/batteries/batteries.json
Ultica "ultra-light disposable battery uses fake item sprite"
Use sprite from ultra-light battery instead of falling back to `battery` for ultra-light disposable battery.
None.
Followed by discussion on Discord.
> Regular battery sprite for disposable ultra-light

- gfx/Chibi_Ultica/tile_info.json
Chibi-Ultica "Re-add Ultica monsters as fillers"
Fixes #1322
> [Chibi] Re-add Ultica monsters as fillers

- .github/workflows/make_release.yml
Infrastructure "automate releases"
To help fris with <https://github.com/Fris0uman/CDDA-Tilesets/pull/9>
To automate what can be automated, this job is perfect for a bot, let them do it
Still on the DOTO list - maybe for later
~~- [ ] Don't compose if there are no changes since previous release~~ 
~~- [ ] Simple automated changelog like this one <https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-04-26-1858>~~
This commit <https://github.com/casswedson/CDDA-Tilesets/commit/623636af939ceab00933deebdcdb507ed3af0ad7> triggers <https://github.com/casswedson/CDDA-Tilesets/runs/6251026427?check_suite_focus=true> making <https://github.com/casswedson/CDDA-Tilesets/releases/tag/2022-05-02>
> feat: automatic releases

- gfx/MShockXotto+/pngs_tall_32x48/monster/mon_nursebot.json
MSX "Fix Nurse bot json"
Fix json to:
- show all three variants
- use same sprite for nurse bot and defective nurse bot in Chibi Ultica
> [MSX] Fix Nurse bot json

- .github/workflows/make_release.yml
None
To fix an error related with the default body of a release, it just compares the changes with itself
plus some other things I wanted to change, one of them is get the logs of the composer, useful when errors pop up the other was to do fewer steps to prepare the assets for a release, this saves like milliseconds, but I do like clean code
The commit you are essencially looking at in this pr
https://github.com/casswedson/CDDA-Tilesets/commit/74aa439b6db0bf0419e857450298ebef9eb0906e
and one that fixes an ultica composer error aka https://github.com/I-am-Erk/CDDA-Tilesets/pull/1337
https://github.com/casswedson/CDDA-Tilesets/commit/20fd236b5b3f0ded7546bc4b5f2c03d65f601be4
They make https://github.com/casswedson/CDDA-Tilesets/releases/tag/2022-05-08-1740
With no tag comparison errors and …
> ft. releaser tweaking

- .github/workflows/make_release.yml
None
Change name to ChibiUltica to match the name of the folder in the game repo
> Fix name of ChibiUltica artifact

- .github/workflows/make_release.yml
None
in preparation for automatic tileset updates for the CDDA repo, the
release artifacts need to be named exactly as the folders in the
`gfx/` folder of CDDA
in CDDA `MshockXotto+` as a release asset here `MShockXotto+`
> fix: msx artifact name

- .github/workflows/make_release.yml
None
also try not to 'fail' before pushing a tag, we don't want to cancel a
release but push a tag anyway
https://github.com/casswedson/CDDA-Tilesets/commit/a0a00eb2afdd1d90c5049aa5df1256dc8f56e532 this commit doesn't make any changes, thus releaser fails, it does it before pushing a tag, pushing tags is similar to making releases I'd like to avoid that
> feat: skip release if there are no changes

- .github/workflows/make_release.yml
None
A few days ago, I asked Fris how to make release notes this pretty <https://github.com/I-am-Erk/CDDA-Tilesets/releases/tag/2022-05-08>
Turns out it is a feature of the releases page, tho you have to do it by hand, fris also pointed me to some api docs that could explain how to automate this
pretty release notes are very desirable, the api docs are confusing, but I got it working after some time
Testing in my cuteclysm fork
see this release <https://github.com/casswedson/CDDA-tileset/releases/tag/2022-05-12-2311> generated by this commit https://github.com/casswedson/CDDA-tileset/commit/5d157eb5b88c739f307a0facacc8cce0eb313c78
This was very useful for figuring out what needed to be done
https://github.com/cli/cli/blob/trunk/.github/workflows/releases.yml
references: …
> feat: auto generate release notes

- .github/workflows/Altica_ci_build.yml
- .github/workflows/Chibi_ci_build.yml
- .github/workflows/HitButton_ci_build.yml
- .github/workflows/Larwick_Overmap_ci_build.yml
- .github/workflows/MD_ci_build.yml
- .github/workflows/Neodays_ci_build.yml
- .github/workflows/Retrodays_ci_build.yml
- .github/workflows/SurveyorsMap_ci_build.yml
- .github/workflows/Ultica_ci_build.yml
- .github/workflows/blb_ci_build.yml
- .github/workflows/hm_build.yml
- .github/workflows/make_release.yml
- .github/workflows/msx_ci_build.yml
None
I use the github runners to compose **all** my changes; it's in my best interest to make performance improvements where possible, the main change here is the removal of `apt update` this saves a little time like under or around ~20 seconds, good enough for a start
I was also experimenting with caching the packages, caching would reduce an action's execution time to mostly the composing step time like 1-2 minutes, at the moment I can't get it to work correctly so here is a partial patch with performance improvements
regular run https://github.com/casswedson/CDDA-Tilesets/actions/runs/2484825641 at 2m 19s
new run https://github.com/casswedson/CDDA-Tilesets/actions/runs/2484970368 at 1m 53s
> feat: minor speed up to composer workflows

- .github/workflows/Altica_ci_build.yml
- .github/workflows/Chibi_ci_build.yml
- .github/workflows/HitButton_ci_build.yml
- .github/workflows/Larwick_Overmap_ci_build.yml
- .github/workflows/MD_ci_build.yml
- .github/workflows/Neodays_ci_build.yml
- .github/workflows/Retrodays_ci_build.yml
- .github/workflows/SurveyorsMap_ci_build.yml
- .github/workflows/Ultica_ci_build.yml
- .github/workflows/blb_ci_build.yml
- .github/workflows/hm_build.yml
- .github/workflows/make_release.yml
- .github/workflows/msx_ci_build.yml
None
I compose **all** my changes using the github runners, it takes a long time ~3 minutes here https://github.com/I-am-Erk/CDDA-Tilesets/runs/6868986119?check_suite_focus=true
It's in my best interest to speed up these boys
Also note that every run will differ by execution time; some randomness with the internet connection idk your guess is a good as mine
First run with this patch ~2 minutes https://github.com/casswedson/CDDA-Tilesets/runs/6870968421?check_suite_focus=true it builds the cache, deps installation takes ~27 seconds, still far better than the ~2m 22s of a previous run
Consecutive runs would spend less than 10 seconds on the deps download step https://github.com/casswedson/CDDA-Tilesets/runs/6871007444?check_suite_focus=true and …
> feat: cache dependencies to speed up composers

- tools/updtset.cmd
Tool for the windows artists that wraps default multiplatform compose.py
Infrastructure "Windows wrapper for compose.py"
This batch script allows artists to set up variables and just doubleclick this file to get composed tileset and put it in game. So it can be tested on the fly.
There are also some checks and useful tips that helps setting artists environment up.
Default run if everything is ok:
Quiet mode:
Some error handling:
It will also try to install pyvips once in case of installed python but missing module.
> [Infrastructure] windows wrapper for the 'compose.py'

- gfx/Larwick_Overmap/pngs_overmap_16x16/dirt_road/dirt_road.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_agricultural.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_hardcoded.json
Larwick "Isherwoods with some misc. agricultural fixes"
Fixes various issues with the Isherwoods special terrain, including parity with non-Isherwoods farm variants; also including lake cabins, farm_* greenhouses, coops, and barns. Reorganized a few agricultural overmap tiles, and cabins
Before:
Isherwoods
Farm_*
After:
Isherwoods
Farm_*
> [Larwick Overmap] Isherwoods and agricultural cleaning

- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_hardcoded.json
- gfx/Retrodays/pngs_tiles_10x10/overmap/field.json
- gfx/Retrodays/pngs_tiles_10x10/overmap/forest.json
- gfx/Retrodays/pngs_tiles_10x10/overmap/forest_thick.json
RetroDays "Partially revert #1446 and #1447"
Revert changes relating to ```special_*``` terrain introduced in #1446 and #1447 in response to https://github.com/CleverRaven/Cataclysm-DDA/pull/59302, in which globally (mostly) fixes issue #1433 instead of needing to fix it for each tileset.
See https://github.com/CleverRaven/Cataclysm-DDA/pull/59302
Rural roads are a bit strange, since I can't seem to find them explicitly spawned outside of Isherwoods, but they are copied from by dirt roads, used almost everywhere, so the changes relating to them in #1446 and #1447 have not been reverted and are not touched by https://github.com/CleverRaven/Cataclysm-DDA/pull/59302; this means for now tilesets will still need to connect them to sprites themselves.
Also, Ultica (and likely forks of it) seems …
> [RetroDays/Larwick Overmap] Partially revert #1446 and #1447

- gfx/NeoDays/pngs_tiles_10x10/items/directional_antenna_f_small_satelitte_dish_0.json
- gfx/Retrodays/pngs_tiles_10x10/item/directional_antenna_f_small_satelitte_dish_0.json
NeoDays "Fixed satellites not using their sprite"
Renamed satellites to their new correct name
Before: 
After:
It seems aliasing (or at least the one done for this change) doesn't work for sprites.
> [NeoDays/RetroDays] Satellites not using sprite

- tools/updtset.cmd
Infrastructure "Changed default behavior and added support for microsoft store python installation"
1) Changed default behavior, now script will update the game directly. /d key also changed - now it allow to compose tileset into different folder
2) Added ability to launch not only python launcher (py) but also python that installed from microsoft store.
> [Infrastructure] Compose wrapper fix

- tools/updtset.cmd
Infrastructure "small fix for updtset.cmd"
- Removed unnecessary backup of fallback.png and tileset.txt (they both available in local repository)
- Added warning about Python from Microsoft Store
> [Infrastructure] Small fix for updtset.cmd

- gfx/MShockXotto+/pngs_tiles_32x32/monster/zombie_fat/mon_zombie_fat.json
None
fix this warning https://github.com/I-am-Erk/CDDA-Tilesets/runs/7881324366?check_suite_focus=true#step:6:66
there was an unused sprite around, use it; one of the variants of the fat zombie to be specific
ci pls test for me
> fix: missing msx tile entry warning

- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_industrial.json
Larwick "Fixed the new occupied lumbermill tiles"
Assigned ```lumbermill*_*_ocu``` the same sprites as lumbermill. Also cleans the lumbermill's entry in the json file.
Before:
After:
> [Larwick Overmap] Occupied Lumbermill

- doc/how-to/autotiles.md
- tools/slice_multitile.py
Re-arrange ISO auto-tiles to ortho layout, and add height
Trying to make working with auto-tiling in ISO tilesets easier. Slicing from rhomboid ISO multitiles was added in #1543. 
However, isometric tiles with a height (like walls) are not possible with rhomboid autotile.
This PR adds options to `splice_autotile.py` that re-arranges ISO sprites into an orto autotile layout, and add a height to them.
Artist can now create the top of walls (or the floot for fences) in the rhomboid, seamless layout.
After using the script, the artist can continue with the sides of the walls in the orto layout.
Usage example:
```
python slice_autotile.py --rearrange-top 66 ...
```
Input:
Output
Thanks @vetall812 for providing the idea and the artwork!
None
> Re-arrange ISO auto-tiles to ortho layout, and add height

- tools/unslice_multitile.py
Unslice ISO spites, add path argument
* Add CLI switch `--iso` to unslice to isometric autotiles
* Add arg `--path` to optionally process images from a path other than `.`
Tried with ISO sprites with and without height
Example input (with height):
Produced output:
*Thanks @vetall812 for providing the iso template*
> Unslice: add path and iso arguments

- .github/workflows/make_release.yml
+8 hours more before a release is generated
the only reason we spend 12 hours doing "nothing" after a release is uploaded is in short I made an ill advised decision, there's no reason to spend time doing nothing when we can just push more of the work done over the week
mostly I assumed if there are problems with a release we should have plenty of time to fix it, some time should be dedicated to this, not this much tho
at this point we'll have 3 hours to watch out for errors and make fixes if any are needed, should be plenty
after this many releases I have more trust in the systems we build time to remove the training wheels
> add a couple hours to the release schedule

- doc/installation_windows.md
Minor fix to line breaks in windows guide
Add double spaces to break line before "OR", followd by alternative script useage
Rendered locally with mdBook
> Minor fix to line breaks in windows guide

- .github/workflows/Altica_ci_build.yml
- .github/workflows/Chibi_ci_build.yml
- .github/workflows/HitButton_iso_ci_build.yml
- .github/workflows/Larwick_Overmap_ci_build.yml
- .github/workflows/MD_ci_build.yml
- .github/workflows/Neodays_ci_build.yml
- .github/workflows/Retrodays_ci_build.yml
- .github/workflows/SurveyorsMap_ci_build.yml
- .github/workflows/Ultica-iso_ci_build.yml
- .github/workflows/Ultica_ci_build.yml
- .github/workflows/blb_ci_build.yml
- .github/workflows/hm_build.yml
- .github/workflows/isomsx_ci_build.yml
- .github/workflows/msx_ci_build.yml
so the artifacts names as published by CI go like, `"tileset name"-"git hash"` now this is fine to anyone familiar with git a lot of stuff uses git hashes to display a "version" or point in history to most other people that's just a bunch of meaningless numbers
I wanna be a little more specific, I modified it to `"tileset name"-dev-git-"git hash"` I took most of this from how neovim does it's nightly release names `v0.8.0-dev-1152-g14610332b` for example this should be a little more clear; this artifact is a development build and that's the most important bit, for the more git accustomed adding a `git` before the hash is for tidiness, clear naming do be good
looking at the artifacts generated by this commit
the ones generated by this commit should also be good …
> more specific artifact names

- gfx/Ultica_iso/pngs_iso_flat_48x36/terrain/t_sidewalk/t_floor.json
Remove sidewalk height_3d
A few pixels of height for sidewalks would be nice, but they do things like this with vehicles:
Tried in-game.
> [Ultica-ISO] Remove sidewalk height_3d

- doc/how-to/autotiles.md
- tools/slice_multitile.py
- tools/slice_variants.py
- tools/unslice_multitile.py
Add Python script to slice into numbered variants
A new script `slice_variants.py`, working like `slice_multitile.py`, but creating numbered sprites and working for multitiles of arbitrary size.
Intended to make it easier to make sprite variants.
Tried on 4x4 and 5x5 iso templates.
Could have added it to `slice_multitile.py`, but did not want to add too much only slightly related functionality to the script.
> Add Python script to slice into numbered variants

- gfx/Ultica_iso/pngs_iso_flat_48x36/terrain/t_sidewalk/t_sidewalk.json
Re-introduce Ultica-ISO sidewalk height.
Sidewalk height was removed in #1611 due to it breaking vehicle look. With this fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/61396, it can be re-introduced.
Tried in-game,
> [Ultica-ISO] Re-introduce sidewalk height

- .github/workflows/Altica_ci_build.yml
- gfx/Altica/layering.json
- gfx/Altica/pngs_human_body_32x36
- gfx/Altica/pngs_human_body_plus_32x48
- gfx/Altica/pngs_human_body_wielded_32x36
- gfx/Altica/pngs_monsters_plus_32x48
- gfx/Altica/pngs_tall_furniture_32x64
- gfx/Altica/pngs_tall_magiclysm_32x64
- gfx/Altica/pngs_tall_monsters_32x64
- gfx/Altica/pngs_tall_overmap_32x64
- gfx/Altica/pngs_tall_terrain_32x64
- gfx/Altica/pngs_tall_vehicle_32x64
- gfx/Altica/pngs_tall_wielded_32x64
- gfx/Altica/pngs_traps_plus_32x48
- gfx/Altica/pngs_ultica-tall_32x64
- gfx/Altica/pngs_vehicle_plus_32x48
- gfx/Altica/tile_info.json
Update symlink and tilesheet of Altica to current Ultica
- Uses the `exclude` feature to simplify the setup
- Include some missing layering sprites which should fix the bug below
- Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/57009
- Add its own layering.json file copy pasted from Ultica as I think otherwise the one currently shipping with the game will not update
Compose without issue
No error message about pans
Pan over lay on oven does display properly
> [Altica] Fix layers and update symlinks

- gfx/Ultica_iso/pngs_incomplete_2x_32x32/monsters
- gfx/Ultica_iso/pngs_incomplete_32x32/items
- gfx/Ultica_iso/pngs_normal_32x32/empty_32x32.png
- gfx/Ultica_iso/tile_info.json
More item and monster symlinks in Ultica-ISO
Include items and monsters from `pngs_incomplete_32x32` via symlinks.
Tried in-game
> [Ultica-ISO] More item and monster symlinks

- .github/workflows/Altica_ci_build.yml
- .github/workflows/Chibi_ci_build.yml
- .github/workflows/HitButton_iso_ci_build.yml
- .github/workflows/Larwick_Overmap_ci_build.yml
- .github/workflows/MD_ci_build.yml
- .github/workflows/Neodays_ci_build.yml
- .github/workflows/Retrodays_ci_build.yml
- .github/workflows/SurveyorsMap_ci_build.yml
- .github/workflows/Ultica-iso_ci_build.yml
- .github/workflows/Ultica_ci_build.yml
- .github/workflows/blb_ci_build.yml
- .github/workflows/hm_build.yml
- .github/workflows/isomsx_ci_build.yml
- .github/workflows/make_release.yml
- .github/workflows/msx_ci_build.yml
see https://github.com/I-am-Erk/CDDA-Tilesets/actions/runs/3243972705/jobs/5319472967#step:6:32 the github workflows complain about a soon to be deprecated command; just upgrade I guess
use what they recommend here:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
check this commit's workflows https://github.com/casswedson/CDDA-Tilesets/commit/b35b0072f3e8c2b36bfa3fada81569c150367858
just a sample cause I disabled most composers in my fork
to be honest, I can't test the state of the release; like I don't know how I used to test it before, but I can't get it to work always some resource integration errors
> upgrade "deprecated" workflow infrastructure

- .github/workflows/make_release.yml
I missed sending the output of a step into the runner's environment; send it so other jobs and steps can read data they need
I also added the trigger `workflow_dispatch` so we can run the workflow at any time, this would solve the potential missing release this week
since the workflow was at least successful at pushing a tag we'll get an incomplete changelog, it needs to be generated by hand later
the interface to `workflow_dispatch` so actions > specific workflow > run
> fix: release errors + run on workflow_dispatch

- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_commercial.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_hardcoded.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_military.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_recreational.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_residential.json
Connects trailer park prefabs, strip malls, stadium z-levels, and other misc. fixes
Connects:
- Trailer park mobile homes
- Trailer park administration building
- Strip malls
- Stadium z-levels
Changes:
- Home improvement superstore roof from ``open_air_magenta`` to ``big_building_light_green``
- ``cabin_strange`` to be consistent with other cabins due to ascii variant working as so
Fixes:
- ``mine_shaft*_east"``
- ``lmoe_*prepperquest``
_Strip mall_
_Stadium z-level_
_Mine shaft_
_Home improvement superstore_
_Trailer park_
Roads were intentionally not fixed; they need a better solution.
> [Larwick Overmap] Mobile homes, strip malls, and other misc. fixes

- .github/workflows/make_release.yml
This PR bumps the tag-exists-action version to v1.1.0 to get rid of _some of_ [these warnings](https://github.com/I-am-Erk/CDDA-Tilesets/actions/runs/3308398934):
> bump tag exists action version

- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_residential.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_waste_junk.json
Connects most of the retirement community tiles and some dumpsite tiles
Connects:
- [Retirement community]:
- Houses with duplex
- Parking lots
- Community building with magenta shop and blue pool
- Administration building with light blue two story building
- Dumpsite edge with brown hive
_Before_
_After_
> [Larwick] Retirement community dump

- .github/workflows/make_release.yml
clean and refactor release workflow to evade github's deprecation plans
_a lot_; remove most actions and logic and stuff that came from the dda release workflow, depend on the github CLI tool for as much as possible, it's free and very powerful
there's one thing I didn't keep, welp I mostly forgot about it till now, the extra check for canceling a release if there are no change between now and last week's release
many releases generated today https://github.com/casswedson/CDDA-Tilesets/releases, the latest and a working example https://github.com/casswedson/CDDA-Tilesets/releases/tag/2023-04-15
a workflow run for more details https://github.com/casswedson/CDDA-Tilesets/actions/runs/4709526358
practicing? I guess to hopefully update/fix some of cdda's super complex, super old CI
> refactor: clean/simplify release workflow

- gfx/MShockXotto+/layering.json
Looks like the national flags can't seem to be hoisted unlike the states, pride, and american flag. This fixes it.
added the necessary json entries in Layering.json
> [MSX] Hoistable National Flags

- doc/style/image/skin-female.png
- doc/style/image/skin-male.png
Fix broken image of female/male sprite in the documentation
I've updated symlinks to the actual sprites. Apparently, those sprites moved ages ago, but not in the documentation. 
None.
AFAIR the doc CI uses my fork of mdBook which should be able handle symlinks
> [Ultica] Fix skin images in documentation

- .github/workflows/ASCII_Overmap_ci_build.yml
- .github/workflows/Altica_ci_build.yml
- .github/workflows/Chibi_ci_build.yml
- .github/workflows/HitButton_iso_ci_build.yml
- .github/workflows/Larwick_Overmap_ci_build.yml
- .github/workflows/MD_ci_build.yml
- .github/workflows/Neodays_ci_build.yml
- .github/workflows/Retrodays_ci_build.yml
- .github/workflows/SurveyorsMap_ci_build.yml
- .github/workflows/Ultica-iso_ci_build.yml
- .github/workflows/Ultica_ci_build.yml
- .github/workflows/blb_ci_build.yml
- .github/workflows/composer_template.yml
- .github/workflows/giantdays_ci_build.yml
- .github/workflows/hm_build.yml
- .github/workflows/isomsx_ci_build.yml
- .github/workflows/msx_ci_build.yml
reduce the amount of code needed to set up new tilesets
this also makes it easier to maintain all the workflows, they now share a file where all the logic and commands are stored
now setting up a tileset testing workflow looks like this:
- where we set the most important parts, like the event triggers and path filtering
after that we call a workflow template, similar to a github action with inputs etc. the file has all the code needed to compile a tileset for testing and pushing the result artifact
```yml
name: GiantDays composer
on:
push:
branches:
- master
paths:
- 'gfx/GiantDays/**'
- '.github/workflows/giantdays_ci_build.yml'
pull_request:
branches:
- master
paths:
- 'gfx/GiantDays/**'
- '.github/workflows/giantdays_ci_build.yml'
jobs:
build:
uses: …
```
> refactor: reusable workflows for tileset composers

- .envrc
- .gitignore
- doc/SUMMARY.md
- doc/installation.md
- doc/installation_nix.md
- flake.lock
- flake.nix
Add support for [nix](https://nixos.org/) in the repository in form of a flake.
Add `flake.nix` with ability to build tilesets and enter a devshell.
```sh
nix build .#UltimateCataclysm
cat result/tileset.txt
````
Produces a working tileset.
It's what I use to comfortably work with tilesets, figured it wouldn't hurt to have this in the repo if there are other madlads who use nix. It's also possible to run reproducible nix builds in the CI now.
Ah. I should probably also add a book building package. Someday..
> Add Nix support

- gfx/MShockXotto+/pngs_tiles_32x32/terrain/t_window_empty/t_window_empty.json
I forgot to give skylight frame the t_open_air sprite as its bg. This fixes it.
- t_open_air bg for skylight frame
Before
After
> [MSX] Give the skylight frame blue tint open air background

- tools/compose.py
make use-all the default behavior when running compose.py
As use-all is the preferred outcome when running compose.py, invert the logic to instead present a `--no-use-all` argument instead, in the event that the user does not want the behavior.
1/ Run script with default arguments, no warning generated and all tiles included.
2/ Run script with `--no-use-all`, get `WARNING handle_unreferenced_sprites` messages
> make use-all the default behavior when running compose.py

- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_blue.json
- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_gray.json
- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_green.json
- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_light_green.json
- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_red.json
- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_white.json
- gfx/NeoDays/pngs_tiles_10x10/items/reading/manual_yellow.json
Adds some books to the appropriate files.
Connects:
"alloy_book", "concrete_book", "reference_firstaid1", "reference_firstaid2", "sa_cryptology_key", "baking_book", "cookbook_liverforkids" and "distilling_cookbook" to manual_blue.json
"sweet_book", "isherwood_herbal_remedies" and "survivalflavor_book" to manual_gray.json
"book_lockpick","vinegar_maker", "offalcooking" and "fermenting_book" to manual_green.json
"tailor_japanese" and "winemaking_beginner" to manual_red.json
"dairy_book" to manual_white.json
"cookbook_indian" to manual_yellow.json
"exodii_wiring_kit_reference" to manual_light_green.json
Before
After
> [NeoDays] Adds some missing books to the appropriate files

- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/cabin/cabin.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/cs_private_park/cs_private_park.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/cs_public_art_piece/cs_public_art_piece.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/cs_public_space/cs_public_space.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/dirt_road/dirt_road.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/evac_shelters/evac_shelters.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/gas/omt_gasstations.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/missile_silo/missile_silo.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/pasture/pasture.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/pools/pools.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/public_pond/public_pond.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/residential.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/river/river.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/road/road.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/road_nesw_manhole/road_nesw_manhole.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/rural_house/rural_house.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/sub_station/sub_station.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/swamp_shack/swamp_shacks.json
- gfx/UltimateCataclysm/pngs_normal_32x32/overmap/trail_small/trail_small.json
- gfx/UltimateCataclysm/pngs_tall_32x64/overmap/wind_turbine/wind_turbine.json
Fixes rotation to some of the overmap JSONs and adds placeholder to others
Added placeholder JSON to the trailer/mobile home road
Added placeholder JSON to the paddock overmap
Fixed dirt road rotation issues and added the missing center sprite ( It was unused "Sorry" )
Fixed rotation to several city building and added JSON to some of them due to different face origin
Fixed rotation of the swamp shack and the wind turbine
Maybe other fixes and tweaks I forgot about
Tested every change so trust me :)
Noticed that some players are still interested in that overmap tileset while it's lacking heavily "Shrug emoji"
> [Ultica] Fixes and tweaks to the overmap

- tools/updtset.cmd
the main wrapper 'updtset.cmd' changed to install specific version of Python and lib-vips if they werent in the system.
First time tileset repository cloned allow you to run updtset.cmd and it will check for Python, pyvips module and libvips.
If any of this part absent in system script will try to download and install them
Known bugs:
on windows 10/11 user may have to manually disable app execution alias in system setting. This happens if python was installed via script.
> [Tools] Added ability to install specific versions of Python and LibVIPS

- gfx/MShockXotto+/pngs_tiles_32x32/terrain/t_card_reader/t_card_science.json
Fixes #2233
Fix the json to use the card reader sprite for science *and* military card reader
Basically there was a mistake in #2162 that attributed the `t_card_military` sprite to `t_card_science` but forgot to also include `t_card_military` itself in the list of id. I've made that mistake before, `--use-all` doesn't work if the sprite is mentionned for something in json, then it needs to list all of the id it will be used for
> [MSX] Fix missing military card reader

- gfx/Ultica_iso/pngs_fillergiant_96x96/aioe_filler_trees
- gfx/Ultica_iso/pngs_fillergiant_96x96/yar_trees
- gfx/Ultica_iso/pngs_giant_96x96/terrain
- gfx/Ultica_iso/pngs_large_64x64/terrain/common
- gfx/Ultica_iso/pngs_large_64x64/terrain/t_tree_fungal_young
- gfx/Ultica_iso/pngs_large_64x64/terrain/t_tree_young
- gfx/Ultica_iso/tile_info.json
- changed z-level height to 108px
- added conception of floor thickness (12px below baseline)
- retraction marked obsolete
- removed unnecessary spaces
- removed filler section that completly coverd by new sprites (trees on 'large' tiles)
- removed unused filler folders
> [Ultica-ISO] Cleanup

- gfx/GiantDays/pngs_large_40x40/mutations/hair/black/overlay_mutation_hair_black.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/blond/overlay_mutation_hair_blond.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/blue/overlay_mutation_hair_blue.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/brown/overlay_mutation_hair_brown.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/gray/overlay_mutation_hair_gray.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/green/overlay_mutation_hair_green.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/pink/overlay_mutation_hair_pink.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/purple/overlay_mutation_hair_purple.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/red/overlay_mutation_hair_red.json
- gfx/GiantDays/pngs_large_40x40/mutations/hair/white/overlay_mutation_hair_white.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/black/overlay_mutation_hair_black.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/blond/overlay_mutation_hair_blond.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/blue/overlay_mutation_hair_blue.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/brown/overlay_mutation_hair_brown.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/gray/overlay_mutation_hair_gray.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/green/overlay_mutation_hair_green.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/pink/overlay_mutation_hair_pink.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/purple/overlay_mutation_hair_purple.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/red/overlay_mutation_hair_red.json
- gfx/GiantDays/pngs_mobs_20x20/characters/overlay/mutation/hair/white/overlay_mutation_hair_white.json
Fixed hair ids for GiantDays
Modified the JSON files for both the 40x40 and 20x20 character hair mutation overlays to reflect newer hair IDs. 
Compiled on mac, and loaded up giantdays on experimental 3eb062c. Looks like all the hair is visible
Did not rename any of the graphics files.  Helps with #2237
> [GiantDays] Re-add hair

- gfx/MShockXotto+/pngs_overmap_32x32/Houses/single_house.json
Add 2farm_11 house to house tile in overmap
Gives a house tile to one of the mutable farm tiles in MSXotto+
> Add 2farm_11 house to house tile in overmap

- tools/check_overmap_coverage.py
The script that try to determine what overmap IDs are covered by sprites in the specific tileset.
First working release.
```
Determining CDDA executable directory:
- CLI argument : not provided!
- ENV variable : D:\vetal_l\CDDA found!
- Launcher  DB : setting exist and same as environment variable.
+ game is here : D:\vetal_l\CDDA
Determining tileset and its location
- No tileset argument provided. Should try to find repository and offer a choice.
- Check if current directory is in the repo.
- Repository found!
Available tilesets:
1. Altica
2. ASCII_Overmap
3. BrownLikeBears
4. Chibi_Ultica
5. GiantDays
6. HitButton_iso
7. HollowMoon
8. IsoMSX+
9. Larwick_Overmap
10. MShockXotto+
11. Mushroom-Dream
12. NeoDays
13. PenAndPaper
14. Retrodays
15. SurveyorsMap
16. Ultica_iso
17. …
```
> [tool] check_overmap_coverage.py

- gfx/MShockXotto+/pngs_overmap_32x32/forest.json
Tile for Lumbermill forest  
It reads as forest on the overmap so now it uses a forest tile.
> [MSX] Lumbermill Forest Overmap

- tools/check_overmap_coverage.py
- tools/special_overmap_symbols.json
Changed Camel to Snake name style
Changed `exit()` to `raise()`
Added `-y` | `--yes` key to remove user input after execution
Added ability to select on of predefined marking symbol `-m` | `--mark`
Added ability to sort results `-s` | `--sort`
Added ability to export result to csv file `-f` | `--file`
Added filtering by name `-n` | `--name`
or by id `-i` | `--id`
Added ability to print file that have sprited ID `-j` | `--json`
different types of filtering:
export results to csv:
last example execution command:
`check_overmap_coverage.py . SurveyorsMap -m 'v' -s percent -i aband -n ware -f aban_ware.csv`
(The dot here reflects my unwillingness to specify the path to the game; I want the script to find it automatically.)
> [tool] Update check_overmap_coverage.py

- doc/style/UltimateCataclysm/summary.md
Per title; super simple documentation cleanup.
Re-orders the bullets on the summary page to match the rendered table of contents, plus fixed the link to the terrain-furniture page.
Tested updated markdown in a markdown editor.
> Ultica Doc fix - broken link/ordering in summary

- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_granularity.json
- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_hardcoded.json
Changes granular swamps to reflect what overmap claims they are, granular isolated towers to watchtower sprite, and adds meadows
Connects various meadows to "two_grass_brown"
Changes: 
- Vague-level swamps look like forests
- Outline and details-level swamps use swamp sprite instead of cyan tree
- Isolated towers use watchtower sprite instead of (office building) tower
_Before_
_After_
> [Larwick] Minor granularity changes and meadows

- gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_residential.json
- gfx/PenAndPaper/pngs_overmap_48x48/2x2/apartment_tower/apartment_tower.json
- gfx/SurveyorsMap/pngs_overmap_24x24/apartment_towers/apartments_con_tower/apartments_con_tower.json
- gfx/UltimateCataclysm/pngs_tall_32x64/overmap/apartments_con_tower/apartments_con_tower.json
https://github.com/CleverRaven/Cataclysm-DDA/pull/75902 added a new overmap - `apartments_con_tower_115`
This pr makes JSON changes for it to be displayed on the map
JSON changes.
`apartments_con_tower_115` looks like other tiles of same building below it in ultica
`apartments_con_tower_115` looks like `apartments_con_tower_015` in other tilesets
The uppermost level of  `apartment_con_new`. Tile to the south of the character is the roof of the stair bulkhead (`apartments_con_tower_115`), which will be added by above mentioned pr. Tile to the west of it is elevator bulkhead's roof (`apartments_con_tower_015`, not changed).
> Add  `apartments_con_tower_115` 

- gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/mutations/overlay_mutation_FLOWERS_0.json
None
Fixes the second tier of flowers being invisible.
Apply fix in https://github.com/CleverRaven/Cataclysm-DDA/pull/76477 and this fix and verify that a character with the mutation has a visible change.
Summary is `None` because it would just be the same summary as the pull request below.
This depends on the following pull request being merged "upstream": https://github.com/CleverRaven/Cataclysm-DDA/pull/76477
> [MSX] Update overlay_mutation_FLOWERS_0.json

- gfx/UltimateCataclysm/layering.json
Add murky water layer JSON to recess
Modified layering.json to make murky water use the same layer sprite as water and clean water for both recess terrain
recess water got graphically visible once again :)
0.i change as Cataclysm-DDA PR 76366 ( jsonifny water_from ) isn't backported to 0.H
> [0.i] [Ultica] Add murky water layer JSON to recess

- gfx/NeoDays/pngs_tiles_10x10/characters/overlay/worn/overlay_female_worn_chainmail_hands.json
- gfx/NeoDays/pngs_tiles_10x10/characters/overlay/worn/overlay_female_worn_chainmail_hauberk.json
- gfx/NeoDays/pngs_tiles_10x10/characters/overlay/worn/overlay_female_worn_chainmail_suit.json
- gfx/NeoDays/pngs_tiles_10x10/characters/overlay/worn/overlay_male_worn_chainmail_hands.json
- gfx/NeoDays/pngs_tiles_10x10/characters/overlay/worn/overlay_male_worn_chainmail_hauberk.json
- gfx/NeoDays/pngs_tiles_10x10/characters/overlay/worn/overlay_male_worn_chainmail_suit.json
With the chainmail graded steel updates, the overlay got broken. This should fix, AFAICT (and was able to test).
Add all new IDs.
Local build, spawn items, works.
I've tried to point to base item instead, but I assume because they're abstract, it doesn't work.
> [NeoDays] fix worn chainmail overlays

- gfx/MShockXotto+/pngs_tiles_32x32/mods/xedra_evolved/character/mutations/BLOODTHORNE_DRUID_AURA_OF_VINES.json
[MSX] Use VINES3 sprite for BLOODTHORNE_DRUID_AURA_OF_VINES
Use VINES3 sprite for BLOODTHORNE_DRUID_AURA_OF_VINES
> [MSX] Use VINES3 sprite for BLOODTHORNE_DRUID_AURA_OF_VINES

- gfx/MShockXotto+/pngs_tiles_32x32/mods/xedra_evolved/character/mutations/BLOODTHORNE_DRUID_AURA_OF_VINES_TRAIT.json
`BLOODTHORNE_DRUID_AURA_OF_VINES_TRAIT` is the trait applied by activating `BLOODTHORNE_DRUID_AURA_OF_VINES`. Narratively, you only have vines sticking out of you if `BLOODTHORNE_DRUID_AURA_OF_VINES` is active and you have `BLOODTHORNE_DRUID_AURA_OF_VINES_TRAIT`, so the sprite should go on `BLOODTHORNE_DRUID_AURA_OF_VINES_TRAIT` so you can tell when it's active
Shift the target from `BLOODTHORNE_DRUID_AURA_OF_VINES` to `BLOODTHORNE_DRUID_AURA_OF_VINES_TRAIT`
> Move sprite from BLOODTHORNE_DRUID_AURA_OF_VINES to BLOODTHORNE_DRUID_AURA_OF_VINES_TRAIT

- gfx/MShockXotto+/pngs_overmap_32x32/overmap_horde/overmap_horde.json
Point `overmap_horde_1` and `overmap_horde_2` to `overmap_horde_3` sprite
Basegame
- overmap_horde_1 and 2 (point at overmap_horde_3 sprite)
> [MSX] Point `overmap_horde_1` and `overmap_horde_2` to `overmap_horde_3` sprite
