Ultimate_Cataclysm/documentation/autotiles.md

Link to template_autotile.png contains Ultimate_Cataclysm which it shouldn't.

Fixed autotile path

---

readme.md

Add one line to `Item tiles` specifying that container should be drawn empty.

Add empty container requirement to readme

---

readme.md

Add basic installation instructions

Add installation instructions

---

Ultimate_Cataclysm/gfx/UltimateCataclysm/pngs_tall_32x64/overlay/wielded/corpses/corpses.json

@barsoosayque @I-am-Erk please check

Fix typo in zombie corpse wielding JSON 🧟‍♂️

---

.github/workflows/ci_build.yml
.github/workflows/make_release.yml

This will now run builds on every push to master as well as every opened PR.

Add CI builds for PRs and master

---

.github/workflows/ci_build.yml

Add missing python packages for build

Fix CI builds

---

gfx/UltimateCataclysm/tile_info.json

Improving compatibility with [Text Fallback Fillers](https://github.com/int-ua/CDDA-Tileset-TFF).

Two new generic filler directories

---

gfx/UltimateCataclysm/pngs_tall_32x64/monsters/mon_zombie_mancroc/mon_zombie_mancroc.json

I wanted to check the zombie in-game but it was just a fallback.  I hope this will fix it.

mon_zombie --> mon_zombie_mancroc

---

gfx/MShockXotto+/pngs_tiles_32x32/character/player_female_0.json
gfx/MShockXotto+/pngs_tiles_32x32/character/player_male_0.json
gfx/MShockXotto+/tile_info.json

Add json for player sprite
Add tile_info.json for composing
Still need to remove a bunch of obsolete sprites

Small MSX update

---

.gitignore
gfx/MShockXotto+/pngs_large_64x80/overlay_wielded_qiang_0.json
gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/wielded/overlay_wielded_qiang_0.json

- Update gitignore
- Fix json left over from #309

[MSX]  Update gitignore for msx tilesheets

---

gfx/UltimateCataclysm/pngs_tall_32x64/furniture/f_machinery/f_machinery.json

Fix machinery background

---

.gitignore

What it says on the tin
So that git stop tracking changes to those tilesheets

Add new tilesheets for Ultica and BLB to gitignore

---

gfx/UltimateCataclysm/tile_info.json

Fixes #340 (workaround, working on the full fix for `compose.py`)

Remove empty filler folders to fix #340 ASAP

---

gfx/MShockXotto+/pngs_tiles_32x32/field/fd_hot_air1_0.json
gfx/MShockXotto+/pngs_tiles_32x32/field/fd_hot_air2_0.json
gfx/MShockXotto+/pngs_tiles_32x32/field/fd_hot_air3_0.json
gfx/MShockXotto+/pngs_tiles_32x32/field/fd_hot_air4_0.json
gfx/MShockXotto+/pngs_tiles_32x32/furniture/f_null_0.json
gfx/MShockXotto+/pngs_tiles_32x32/misc/explosion_medium_0.json
gfx/MShockXotto+/pngs_tiles_32x32/misc/explosion_weak_0.json
gfx/MShockXotto+/pngs_tiles_32x32/terrain/t_null_t_sliding_wall_o_0.json

- remove useless jsons to silence compose warnings

[MSX] Remove useless jsons

---

gfx/UltimateCataclysm/pngs_normal_32x32/terrain/splitrail/t_splitrail_fence/t_splitrail_fence.json

Seasonal background for splitrail

---

.gitignore

Use wildcard to ignore any `.png`in root folder of tileset inseatd of listing all the tilesheets

Update gitignore to include any png in root folder of tileset

---

.github/workflows/blb_ci_build.yml

Add workflow to build BrownLikeBears

[BLB] Add workflow to build BrownLikeBears

---

gfx/UltimateCataclysm/pngs_incomplete_32x32/vehicle/seats/seats.json

Applies existing sprites for back seats

Apply existing sprites for back seats

---

gfx/MShockXotto+/Credit.txt

Add credit.txt that list the contributors that added to MSX, and the tilesets that MSX inherited from. The list is non exhaustive it just the names I found in the old MSX files.

[MSX] Credit contributors involved in MSX before it got on this repo

---

.github/workflows/Chibi_ci_build.yml

Remove `--obsolete-fillers ` from chibi_ultica workflow

Don't use --obsolete-fillers option

---

.github/workflows/pr_validator.yml

Infrastructure "Add a PR validator to the workflow"
- Add a PR validator to the workflow
See if it triggers for this PR and works properly
It's mainly a copy-paste from the one CleverRaven uses

Add a PR validator to the workflow

---

.github/pull_request_template.md

Infrastructure "'Information' is generally singular."
Makes "Additional informations" singular.

Grammar/style: "Information" is generally singular

---

doc/how-to/image/f_bench_autotile_labels.png
doc/how-to/image/multitile_grid_4x4.png
doc/how-to/image/multitile_grid_4x4_tall.png
doc/how-to/image/t_grass_multitile.png

None
Fix absolute paths in symlinks

fix doc images symlinks

---

tools/recolor_season_variants.py

Infrastructure "pycodestyle recolor_season_variants.py"
pycodestyle and other edits and comments
TODO

pycodestyle recolor_season_variants.py

---

tools/slice_multitile.py

Infrastructure "slice_multitile.py support for overmap multitiles"
Done in #700 #702

Infrastructure "slice_multitile.py support for overmap multitiles"

---

gfx/UltimateCataclysm/pngs_normal_32x32/overmap/forest_trail/forest_trail.json
gfx/UltimateCataclysm/pngs_normal_32x32/overmap/road/road.json
tools/slice_multitile.py

Ultica "Convert overmap road and forest trail JSONs to multitile format"
Requesting help.

Ultica "Convert overmap road and forest trail JSONs to multitile format"

---

gfx/UltimateCataclysm/pngs_normal_32x32/terrain/t_slime/t_slime.json

Ultica "Fixed t_slime no longer working with --use-all because it was used for overmap"

---

tools/slice_multitile.py

Infrastructure "slice-multitile.py: opt-in --add-empty-bg, removed --overmap"
Done on #723

Infrastructure "slice-multitile.py: opt-in --add-empty-bg, removed --overmap"

---

gfx/UltimateCataclysm/pngs_normal_32x32/overmap/generic_special/ranch_camp.json
gfx/UltimateCataclysm/pngs_normal_32x32/overmap/pasture/pasture.json
gfx/UltimateCataclysm/pngs_normal_32x32/overmap/rural_house/rural_house.json
gfx/UltimateCataclysm/pngs_normal_32x32/overmap/silo/silo.json

Ultica "Ultica overmap ranch camp json"
Adds overmap ranch camp json

Ultica overmap ranch camp json

---

gfx/NeoDays/pngs_tiles_10x10/vehicle/neodays_tempfix.json

NeoDays "vehicle fix"
Adds sprites for the new vehicle parts in https://github.com/CleverRaven/Cataclysm-DDA/pull/50632

Neodays vehicle fix

---

gfx/BrownLikeBears/pngs_tiles_20x20/vehicle_part/blb_tempfix.json

BLB "vehicle temporary fix"
Temporary vehicle sprites fix for when https://github.com/CleverRaven/Cataclysm-DDA/pull/50632 gets merged

BLB vehicle temporary fix

---

gfx/MShockXotto+/pngs_tiles_32x32/vehicle/msx_tempfix.json

MSX "temporary vehicle fix"
Adds a temporary vehicle fix json for MSX for when https://github.com/CleverRaven/Cataclysm-DDA/pull/50632 gets merged

Msx temporary vehicle fix

---

gfx/SurveyorsMap/pngs_overmap_24x24/houses/house_wooded/house_wooded.json

Smap "Fix bad ID"
Erk was too fast
checked artifact in game.

[Smap] Update house_wooded.json

---

tools/recolor_season_variants.py

HM "Upgrade HM recolor script to recolor any source seasonal palette"
Reason:
I've noticed that @secretstamos created lot of sprites in "the sketchbook" using palettes other then SPRING.
If one would like to use them to fill in the gaps in the tileset it would require manual recoloring.
Previous script recolored only files named `generic.png` that used SPRING palette to generate the rest.
Solution:
Upgraded script can recolor any allowed source palette as long as you name the file `<season>.png` (for example `summer.png`) to tell it what it's working with.
For legacy reasons I kept the functionality for the `generic.png` too.
I also added some guidelines inside the script (that will be ported to the tileset's doc too Soon™).
I tested it by using the script to recolor every supported …

Upgrade recolor_season_variants.py

---

gfx/Altica/pngs_character_32x36/characters.json
gfx/Altica/pngs_character_32x36/player_female.json

Altica "Fix NPC sprite"
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/56178 as soon as the tileset will get updated

[Altica] Fix NPC sprite

---

.github/workflows/Altica_ci_build.yml
.github/workflows/Chibi_ci_build.yml
.github/workflows/HitButton_ci_build.yml
.github/workflows/Retrodays_ci_build.yml
.github/workflows/SurveyorsMap_ci_build.yml
.github/workflows/Ultica_ci_build.yml
.github/workflows/blb_ci_build.yml

Infrastructure "Fix github Actions"

Try to fix gha with `sudo apt update`

---

gfx/BrownLikeBears/pngs_tiles_20x20/items/cloth/gloves_bag_0.json
gfx/BrownLikeBears/pngs_tiles_20x20/items/cloth/socks_bag_0.json
gfx/UltimateCataclysm/pngs_normal_32x32/fake_item.json

Infrastructure "Fix some json"

Fix some json

---

gfx/MShockXotto+/Credit.md
gfx/MShockXotto+/Credit.txt

MSX "Improve attribution of pre-migration artists"
Improves attribution by linking to the main repo history
Obsoletes #1366

[MSX] Improve attribution of pre-migration artists

---

gfx/BrownLikeBears/tileset.txt

Update BrownLikeBears pre-decomposition credits

---

gfx/HitButton_iso/tileset.txt
gfx/MShockXotto+/Credit.md
gfx/MShockXotto+/tileset.txt
gfx/NeoDays/tileset.txt
gfx/Retrodays/tileset.txt

None
Update credits of decomposed tilesets
Fixes #1369
Also move credits from Credits.md to tileset.txt for MSX to keep it inline with the rest

Update credits of decomposed tilesets

---

gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_commercial.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_hardcoded.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_industrial.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_military.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_public_institutional.json

Larwick "Fixes simple Z-levels related tiles and adds light industry and fema (non-refugee) camps"
Fixes Z-levels for:
- Evac shelters (underground)
- Infested LMOE shelters (underground)
- Land prisons (2nd and 3rd floors)
- 2nd floor of new electronics and gun store
- A roof corner of lumbermill buildings (_0_0)
- Stone barns (2nd and 3rd floors)
- Slime pits (0 and -1 z-levels)
- Cathedrals (2nd and 3rd floors)
Adds/connects:
- Light industry
- FEMA camps (non-refugee)
- Cabin prepper cabin and shelter
Before:
After:
I also have begun changing how the json files are organized, noticeable with fema camps and evac shelters currently.

[Larwick Overmap] Z-levels, light industry, and fema camps

---

.github/workflows/isomsx_ci_build.yml

None
I noticed there were two identical msx composer workflows; one is intended to compose the iso version of msx, I fixed it.
good thing someone before me made the workflows to be pretty easy to edit
Download the generated artifact and load a game
https://github.com/casswedson/CDDA-Tilesets/actions/runs/2642769592

fix: isomsx composer

---

.github/workflows/make_release.yml
gfx/HitButton_iso/tileset.txt

Infrastructure "Add SmashButton iso to the release"

Add SmashButton iso to the release

---

gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_hardcoded.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_military.json
gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_public_institutional.json

Larwick "Adds some homes/bases, along with some simple cleaning"
Adds:
- Blacksmith/Gunsmith home
- Potter's cottage
- Underground cave
- Various Triffid portions
- 
Changed: 
- Some firestations from using a brown urban building to the red firestation
- 
Cleaned:
- Slimepit
- Dermatick
- Shipwreck
- Boat rentals
- Lighthouse
- Lmoe
- Bunker
- Radio towers
Before:
After:

[Larwick Overmap] House cleaning

---

tools/slice_multitile.py

Add ISO support  for `slice_multitile.py` autotile.
Add CLI switch `--iso`.
Slices a multitile sheet like this:
into ISO tiles like this:
Inspected resulting tiles and JSON.
Tested in-game. Screenshot shows the above sheet used for `t_dirt` with Ultica-ISO. Note that there is also `t_grass_dead` in the scene, which uses the same sprites, but does not connect with dirt.

Add ISO support  for `slice_multitile.py` autotile

---

doc/README.md
doc/SUMMARY.md
doc/installation_windows.md
tools/compose.py
tools/generate_preview.py
tools/set_game_path.cmd
tools/set_tileset.cmd
tools/set_vips_path.cmd
tools/slice_multitile.py
tools/unslice_multitile.py
tools/updtset.cmd

Easy to use, self-contained tileset update script
Rework `updtset.cmd` and add helper scripts to artists can set up their environment and run updates without needing to touch the command line.
Further, it is not necessary anymore to modify `updtset.cmd` for the local setup. Once environment variable `CDDA_PATH` is set, it should just work out ofthe box with double click. A helper for setting up the variable is also provided.
* not available as as environment variable (both), and
* not given as script parameter (tileset)
* ~~(required as the pre-compiled game does not contain that file)~~
Tried it out in it's different variations.
Usage without touching Command line, fixed tileset:
1. Drag&drop game directory onto `set_game_path.cmd`
2. Drag&drop `libvips` directory onto …

Easy to use, self-contained tileset update script

---

gfx/UltimateCataclysmIsometric/tile_info.json

Add auto-retract parameters to make use of the new feature added by https://github.com/CleverRaven/Cataclysm-DDA/pull/60881.
Add the parameters
Composed and tested in game.
What it does:

[Ultica ISO] Add auto-retract parameters

---

tools/updtset.cmd

Remove unnecassary printing of path to compose script
Remove the `echo`
Run the script.

Minor fix for update script

---

gfx/HitButton_iso/pngs_full_iso_16x20/terrain/t_stairs_down_t_low_stairs_begin_0.json
gfx/HitButton_iso/pngs_full_iso_16x20/terrain/t_stairs_up_t_low_stairs_end_0.json

Wooden stairs now have actual sprite
Connected wooden stairs (up/down) to standard stairs variants

[Smashbutton] Fixed wooden stairs

---

gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/crops
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_ash
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_black_eyed_susan
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_bluebell
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_boulder_medium
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_boulder_small
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_burdock
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_carrot_wild
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_chamomile
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_chicory
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_dahlia
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_dandelion
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_datura
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_flower_fungal
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_flower_spurge
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_flower_tulip
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_indoor_plant
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_lily
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_lotus
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_mustard
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_mutpoppy
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_rubble
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/f_sunflower
gfx/Ultica_iso/pngs_normal_offset_32x32/furniture/lily_pad
gfx/Ultica_iso/tile_info.json

Symlink Ultica plants in Ulsica-ISO
Add symlinks
Tried in-game

[Ultica-ISO] Symlink Ultica plants

---

.github/workflows/make_release.yml
gfx/Ultica_iso/README.md

Add Ultica-ISO to releases, and thus to the game
Add the required CI stuff.
Add a link to the artifacts to the tileset's README file.
Can't test. Next release will show (but the change is very simple).

[Ultica-ISO] Add tileset to releases

---

.github/workflows/msx_ci_build.yml
gfx/MShockXotto+/layering.json

Layering for hoistable flags in MSX
Add layering for flags to implement https://github.com/CleverRaven/Cataclysm-DDA/pull/61551
Tried in-game (see screenshot).

[MSX] Layering for hoistable flags

---

gfx/NeoDays/pngs_tiles_10x10/field/fd_flame_burst.json
gfx/NeoDays/pngs_tiles_10x10/furniture/utility/f_bathtub.json
gfx/NeoDays/pngs_tiles_10x10/furniture/utility/sink/f_sink.json

Fixes single bathtubs, sinks, and fire for some circumstances.
Fixes:
- Bathtub
- Sink
- Fire
_Before_
_After_
Partially patches https://github.com/CleverRaven/Cataclysm-DDA/issues/61653 , but only for NeoDays, and there are likely other tiles affected.

[NeoDays] Fix sinks, bathtubs, fire

---

doc/installation_windows.md

Update link to launcher in the doc

---

gfx/Altica/tile_info.json

[Altica] Fix car offset

---

gfx/MShockXotto+/pngs_tiles_32x32/terrain/t_window_empty/t_window_empty.json

Give skylight frame sprite.
Skylight frame using the `t_window_empty.png` sprite

[MSX] Skylight Frame

---

gfx/UltimateCataclysm/pngs_normal_32x32/terrain/t_window_and_variants/t_window.json

Fix empty window frame
Fixes #1854

[Altica/Chibi] Fix empty window frame

---

gfx/UltimateCataclysm/pngs_large_64x64/overmap/bridge/bridge.json

Fix bridge ramp orientation
Fixes #1788
Just swap the sprites in json

[Ultica] Fix bridge ramp orientation

---

.github/workflows/ASCII_Overmap_ci_build.yml
.github/workflows/Altica_ci_build.yml
.github/workflows/Chibi_ci_build.yml
.github/workflows/HitButton_iso_ci_build.yml
.github/workflows/Larwick_Overmap_ci_build.yml
.github/workflows/MD_ci_build.yml
.github/workflows/Neodays_ci_build.yml
.github/workflows/Retrodays_ci_build.yml
.github/workflows/SurveyorsMap_ci_build.yml
.github/workflows/Ultica-iso_ci_build.yml
.github/workflows/Ultica_ci_build.yml
.github/workflows/blb_ci_build.yml
.github/workflows/book.yml
.github/workflows/editorconfig_conformance.yml
.github/workflows/hm_build.yml
.github/workflows/isomsx_ci_build.yml
.github/workflows/msx_ci_build.yml

I see warnings about an old node version, deprecation warning or whatever fix fix fix
this is just updating the `actions/upload-artifact` action to v3

ci: address deprecation warnings

---

.github/workflows/ASCII_Overmap_ci_build.yml
.github/workflows/Altica_ci_build.yml
.github/workflows/Chibi_ci_build.yml
.github/workflows/HitButton_iso_ci_build.yml
.github/workflows/Larwick_Overmap_ci_build.yml
.github/workflows/MD_ci_build.yml
.github/workflows/Neodays_ci_build.yml
.github/workflows/Retrodays_ci_build.yml
.github/workflows/SurveyorsMap_ci_build.yml
.github/workflows/Ultica-iso_ci_build.yml
.github/workflows/Ultica_ci_build.yml
.github/workflows/blb_ci_build.yml
.github/workflows/hm_build.yml
.github/workflows/isomsx_ci_build.yml
.github/workflows/make_release.yml
.github/workflows/msx_ci_build.yml

this should fix the ci suite; I want green checks everywhere
run apt update before install since apt suggest it https://github.com/I-am-Erk/CDDA-Tilesets/actions/runs/5776441436/job/15655575123#step:3:66

fix ci suite

---

.github/workflows/giantdays_ci_build.yml
.github/workflows/make_release.yml

add support so it gets automatically tested, and add it to the releases so at some point it'll be merged into cataclysm proper
workflow run: https://github.com/casswedson/CDDA-Tilesets/actions/runs/5850290900
release run supporting it: https://github.com/casswedson/CDDA-Tilesets/actions/runs/5850343234
release workflow output: https://github.com/casswedson/CDDA-Tilesets/releases/tag/2023-08-14

ci support for giantdays tileset

---

tools/git_symlinks.cmd

When starting using repository on windows system it is usual that symlinks cannot be created or followed.
This script gives a link to the Microsoft site that explain how to enable symlinks and execute commands that enable symlinks in repository if its already on the system.
git_symlinks.cmd script in /tools

[Tools] Added script that change default Git behavior on windows systems

---

gfx/ASCII_Overmap/pngs_ASCIITiles_10x10/json_legacy/from_data.json

Update new tiles.
Update new tiles.

[ASCII Overmap] few updates

---

doc/SUMMARY.md

I made a mistake in a previous PR and now have to fix it
changed `summary` to `SUMMARY` as file names

[Docs] SUMMARY links capitalized

---

tools/updtset.cmd

- added link to the docs in repo
- added key (-k) that skips ssl check for curl
- fixed pip upgrade command

[Tools] Update for updtset.cmd

---

tools/slicemt.py

- Added the /q key for the updtset call to remove unnecessary information.
- Added the creation of the /source/.scratch file, so the composer ignores the source folder.

[Tools] Update slicemt.py

---

gfx/UltimateCataclysm/pngs_human_body_32x36/overlay/mutations/arachnid_arms/arachnid_arms.json

Adds a suggested change by Crow\NoddingCrow to make Arachnid arms and Arachnid limbs use the same sprite.
Changed JSON of arachnid_ams to cover both of Arachnid limbs and Arachnid arms
OH GOD IT GROWED SPIDER LIMBS OUT OF HIS SKIN 0.0

[Ultica] Fix for Arachnid arms mutation by Crow\NoddingCrow

---

gfx/UltimateCataclysm/pngs_normal_32x32/vehicle/vehicle_parts_placeholder.json

Adds a placeholder JSON for industrial trash can by hoasd1
Added a placeholder JSON for industrial trash can because someone wanted to add a floor to it

[Ultica] A small vehicle part placeholder request :)

---

gfx/UltimateCataclysm/pngs_normal_32x32/overmap/dirt_road/dirt_road.json

Same as [#2343](https://github.com/I-am-Erk/CDDA-Tilesets/pull/2343) but for Ultica
Before:
After:

[Ultica] Update rural_road/dirt_road

---

gfx/Larwick_Overmap/pngs_overmap_16x16/dirt_road/dirt_road.json

[#2343](https://github.com/I-am-Erk/CDDA-Tilesets/pull/2343) but for Larwick Overmap
Before:
After:

[Larwick Overmap] Update rural_road/dirt_road

---

.github/workflows/composer_template.yml
.github/workflows/make_release.yml

to get rid of deprecation warnings

update checkout action to v4

---

gfx/SurveyorsMap/pngs_overmap_24x24/signs/empty_lots.json

Add ID's for a few construction/vacant lots.
Compiled tile set and reviewed in game.

[SurveyorsMap] add vacant lots IDs

---

tools/special_overmap_symbols.json

Added player and NPC IDs to the helper file

[Tools] Update special_overmap_symbols.json

---

tools/check_overmap_coverage.py

added support for granular overmap objects

[tools] Check OM coverage script. Fix for granular view.

---

gfx/ASCII_Overmap/pngs_ASCIITiles_10x10/json_legacy/from_data.json

Updates new tiles
updates new tiles, deletes obsoletes?

[ASCII overmap] update new tiles

---

doc/style/PenAndPaper/colors.md
doc/style/PenAndPaper/fallback.md
doc/style/PenAndPaper/summary.md
doc/style/summary.md

First couple of documents about `Pen And Paper Overmap` tileset

[P&P] Docs first commit

---

.github/workflows/PenAndPaper_ci_build.yml
.github/workflows/make_release.yml

Add workflows for PendAndPaper tileset
Add workflows for PendAndPaper tileset

Add workflows for PendAndPaper tileset

---

gfx/MShockXotto+/pngs_overmap_32x32/pond_field.json

Ranch pond uses overmap pond tile
Adds an additional terrain to pond tile

[MSX+] Make ranch pond use overmap pond tile

---

.github/workflows/composer_template.yml

If it exists copy layering.json in the artefact
If it exists copy layering.json in the artefact

Add layering.json to build artefacts

---

gfx/Larwick_Overmap/pngs_overmap_16x16/go_overmap_terrain_waterbody.json

[Larwick] Use shallow water for stream
Stream
I initially wanted to make it a blue line like roads and forest trails but I failed to make it connect properly

[Larwick] Use shallow water for stream

---

.github/workflows/composer_template.yml

fix upload-artifact version
Use v4 version instead of the deprecated one

fix upload-artifact version

---

gfx/MShockXotto+/pngs_tiles_32x32/mods/mindovermatter/monsters/feral_lab_psychics/mon_feral_scentist_psychic.json
gfx/MShockXotto+/pngs_tiles_32x32/mods/mindovermatter/monsters/feral_lab_psychics/mon_feral_security_captain_psychic.json
gfx/MShockXotto+/pngs_tiles_32x32/mods/mindovermatter/monsters/feral_lab_psychics/mon_feral_security_psychic.json

[Bugfix]
Forgot to paint/add json file with shadows for Mind Over Matter lab psychics
Add 3 json files 
- mon_feral_scentist_psychic.json
- mon_feral_security_captain_psychic.json
- mon_feral_security_psychic.json

[MSX] [MoM] Some forgotten shadows for Feral lab psychics

---

gfx/MShockXotto+/pngs_large_64x80/monsters/rid_mon_horse.json
gfx/MShockXotto+/pngs_large_64x80/monsters/rid_mon_horse_police.json
gfx/UltimateCataclysm/pngs_large_ridden_64x64/rid_mon_horse.json

Fixes #2617
Before:
After:
Couldn't find horse riding sprites in any other tileset

Use rid_mon_horse for mon_horse_police

---

gfx/UltimateCataclysm/pngs_human_body_32x36/overlay/worn/bodysuits/robofac_jumpsuit_f.json
gfx/UltimateCataclysm/pngs_human_body_32x36/overlay/worn/bodysuits/robofac_jumpsuit_m.json

Fix hub 01 jumpsuit sprite
The hub 01 jumpsuit has been variantized but the sprites haven't been fixed accordingly.
I don't know how to test.
Am I doing this right?

Fix hub 01 jumpsuit id

---

gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/worn/overlay_female_worn_sheriffshirt_0.json
gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/worn/overlay_male_worn_sheriffshirt_0.json

Sheriff shirts are not variants of postman shirts and the old ids are obsolete.
Fix the sheriff shirt id.
None.

Fix sheriff shirt id
